# Generated by Django 3.2.23 on 2023-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='upload/')),
                ('product', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
