# Generated by Django 3.2.23 on 2023-12-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cemail', models.CharField(max_length=30)),
                ('ccomment', models.CharField(max_length=100)),
            ],
        ),
    ]
