# Generated by Django 3.2.23 on 2023-12-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
