# Generated by Django 3.2.23 on 2023-12-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20231229_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartitem',
            new_name='Product',
        ),
    ]
