# Generated by Django 3.2.23 on 2024-01-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20231229_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
